[platformio]
src_dir = .  ; Dòng này cực quan trọng: Bảo nó tìm code ngay tại đây

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 9600
lib_deps =
    PubSubClient
    ArduinoJson
    https://github.com/mobizt/Firebase-ESP-Client.git
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    claws/BH1750